name = "msc-project-workers"
main = "src/index.js"
compatibility_date = "2025-11-25"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "msc-project-api.guestliang.icu/*", zone_name = "guestliang.icu" }
]

[[d1_databases]]
binding = "MScPJ_DB"
database_name = "msc-project-25-26"
database_id = "735dfb2d-1996-4047-89c4-44885fbdcda6"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1